name: k8s CI

on:
  push:
    branches:
      - k8s-deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t my-node-app .

